version: '3.8'

services:

  frontend:
    image: front
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: back
    environment:
      - REDIS_HOST=re
    ports:
      - 8080:8080
    container_name: backend

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: re


