version: '3.8'

services:

  frontend:
    image: ml-front
    ports:
      - 3000:3000
    container_name: ml-frontend

  backend:
    image: ml-back
    ports:
      - 5000:5000
    depends_on:
      - training
    volumes:
      - model:/src/app/model
    container_name: ml-backend

  training:
    image: training
    volumes:
      - imgs:/src/app/imgs
      - model:/src/app/model
    container_name: training


volumes:
  imgs:
  model:



